name: npm
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - run: npm ci
            - name: Publish
              uses: JS-DevTools/npm-publish@a25b4180b728b0279fca97d4e5bccf391685aead # v2.2.0
              # only on default branch
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              with:
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

    renovate:
        name: renovate
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        needs: build
        uses: urcomputeringpal/.github/.github/workflows/renovate.yaml@main
        with:
            renovate_app_slug: ur-renovate
            onboarding: "true"
        secrets:
            RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
            RENOVATE_APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
